spring.application.name=inovagab
server.port=8080

# Conexão com o Cluster MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://admin_inovagab:Abc123@cluster0.xxxxxxx.mongodb.net/inovagab_db?retryWrites=true&w=majority